# install! 'cocoapods', :warn_for_multiple_pods => false
install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false

platform :ios, '12.0'

workspace 'TextlayoutDemo.xcworkspace'

target 'TextlayoutDemo' do
    project 'TextlayoutDemo.xcodeproj'
    pod 'LynxTextra', :path => '../../../../'
end

target 'LynxTextraDemo' do
    project 'LynxTextraDemo/LynxTextraDemo.xcodeproj'
    pod 'LynxTextra', :path => '../../../../'
    pod 'json_parser', :path => '../../../../'
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end