install! 'cocoapods', :deterministic_uuids => false, :integrate_targets => false
use_frameworks!

platform :ios, '12.0'

workspace 'TextlayoutDemo.xcworkspace'

target 'TextlayoutDemo' do
    project 'TextlayoutDemo.xcodeproj'
    pod 'LynxTextra', :path => '../../../../'
end

target 'LynxTextraDemo' do
    project 'LynxTextraDemo/LynxTextraDemo.xcodeproj'
    pod 'LynxTextra', :path => '../../../../'
    pod 'json_parser', :path => '../../../../'
end